### ISSUE TITLE
New action to implement in-page variables (placeholders)

### ISSUE THREAD

**Issue by wikkawik** [bakoontz/WikkaWiki#1138]
I envision an action that does something like this:

{{variable name="version" value="1.3.4"}}
...
Blah blah blah ??version?? ...

where a simple substitution for ??version?? is made when rendering the page.

**Comment by PLG** [comment]
Implementing variables across the wiki brings with it the same security issues that pages have. Which users are allowed to access the variables, etc. Why not use pages as variables then?

The version functionality above can theoretically be achieved with just a page include, but version info is admin only. The action `{{wikkaversion}}` already exists, but it is admin only. I'm not sure if the interwiki include would work. I haven't tried.

The email functionality can be simulated with just an include; create a page called Email with the content `[[mailto: info@maildomain.net]]` and include it as `{{include page="Email}}`. Note that including an Email page as `[[mailto: {{include page="Email"}} ]]`will not work. 

It would be interested to know of a scenario where the variables as described above would be needed; can't be implemented using an include.
