### ISSUE TITLE
Invalid XHTML Markup

### ISSUE THREAD

**Issue by jkl3** [bakoontz/WikkaWiki#1171]
The wiki formatter does not check whether XHTML tags are closed in the reverse order that they were opened.  For example, the wiki code `**//bold italic**//` produces the invalid XHTML markup
`<strong><em>bold italic</strong></em>`
where the tags are closed in the wrong order.

**Comment by bakoontz** [comment]
This is more an issue of how the parser works.  Currently, it's a token-based parser, and has no way of "looking ahead" to determine if (1) there is a matching format token or (2) if the format tokens are nested in the correct order.  To resolve this problem, a recursive parser would need to be implemented so account for embedded format tokens and to parse them in correct inner-to-outer order.  

I would argue that with a token-based parser, the //**bold italic//** string is ambiguous as best:  Did the creator intend to italicize "**bold italic", or bold  "bold italic//"? A left-to-right based parser would parse the former; a right-to-left parser (as the C language uses) would parse the latter.  A recursive parser would need to determine how to deal with this in a reasonable way.
