### ISSUE TITLE
preg_replace warning in Geshi.

### ISSUE THREAD

**Issue by klenwell** [bakoontz/WikkaWiki#1256]
Locally, I'm running `1.4.0-pre` and I'm seeing this error on a number of pages:

> Warning: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in 3rdparty/plugins/geshi/geshi.php on line 2137

I think it's pages that involve the display of source code using the `%% ... %%` syntax.

Is this the plugin it's using?

- https://github.com/GeSHi/geshi-1.0

Would updating to the lastest version of that code (or whatever code it's using) fix the issue?

**Comment by oemunoz** [comment]
You are right @klenwell, I test GeSHi 1.0.9.0 Released (first to support php7), works like a charm.

[GeSHi is now officially available on GitHub](http://blog.benny-baumann.de/?cat=3)

https://github.com/GeSHi

**Comment by bakoontz** [comment]
It appears this option was removed in 1.0.9.0, which is the version currently installed as of 1.4.1.
