### ISSUE TITLE
Editing page results in 403.shtml page

### ISSUE THREAD

**Issue by jugdemon** [bakoontz/WikkaWiki#1272]
I have a page with multiple sections, each section is structured like this:

```
====Title====
//Some Text//

Other Text
```
I ran into this bug, when "Other Text" accidentally started with "Get". Trying to store the page will result in the following behaviour:

Instead of saving the currently edited page, it leads me to a new page named "403.shtml" while the URL still displays the old page. The changes to the old page are not submitted.

While I am not sure, I presume that this "Get" is somehow misinterpreted as the HTTP GET command and somehow leads to the new page.

**Comment by jugdemon** [comment]
I found a similar issue when starting with a paragraph with "Move".

**Comment by bakoontz** [comment]
Hi @jugdemon...I can't seem to replicate this using your example. What version of WikkaWiki are you running?  This actually sounds like a server issue, as the stock install of WikkaWiki doesn't use a 403.shtml error page.  Can you post your .htaccess file?

**Comment by jugdemon** [comment]
Dear @bakoontz, I am running 1.3.7 installed with the softaculous installer on a namecheap server. I just informed Softaculous that there is a new version of WikkaWiki. 

There is a htaccess file at the root of the website which contains: 

```
### STOP REFERRER SPAM
SetEnvIfNoCase Referer ".*(adultsite|picturesplace|learnthebiz|pi-o|erotica|ghettoinc|port5|bulk-email|camgirls|paris-hilton|modelos|kredit|handyflirt24|versicherung|wwww|erotower|krank|x-1000|flirtnet|blowjob|agedwife|in-the-vip|boysfirsttime|milf|captain-stabbin|tranny|erotik|fetish|frauen|hardcore|fick|krankenversicherung|jinnan-cross|8thstreet|xxx|XXX|ficken|fuck).*" BadReferrer

order deny,allow
deny from env=BadReferrer

<IfModule mod_rewrite.c>
	# turn on rewrite engine
	RewriteEngine on

	# if request is a directory, make sure it ends with a slash
	RewriteCond %{REQUEST_FILENAME} -d
	RewriteRule ^(.*/[^/]+)$ $1/

	# if not rewritten before, AND requested file is wikka.php
	# turn request into a query for a default (unspecified) page
	RewriteCond %{QUERY_STRING} !wakka=
	RewriteCond %{REQUEST_FILENAME} wikka.php
	RewriteRule ^(.*)$ wikka.php?wakka= [QSA,L]

	# if not rewritten before, AND requested file is a page name
	# turn request into a query for that page name for wikka.php
	RewriteRule ^(.*)$ wikka.php?wakka=$1 [QSA,L]
</IfModule>
```

I hope this helps.

Best wishes

**Comment by bakoontz** [comment]
@jugdemon .htaccess looks fine. I just installed 1.3.7 and copied over your text example.  Tried both Get and Move, couldn't replicate the error.  

Is your wiki public-facing?  I could take a look if it is.

**Comment by bakoontz** [comment]
That is plain weird. “Put” also triggers it. But there has to be a header
preceding the word first. There is no code in the wiki parser that searches
for these terms. Let me see if I can try and replicate it.

**Comment by jugdemon** [comment]
@bakoontz Thank you for doing down the deep end and figuring this out.

In the meantime softaculous updated to version 1.4, but the error (expectedly) persists.

The error log is lamentably empty, and the usual log only shows normal activity. Wherever that zealous  piece of code sits, it doesn't log with my provider. It might be part of the softaculous software management - I will inquire there and report back in case that they are the cause so you know what is going on.

By the way, thank you for this great wiki-system, it is simple and gets the job done and I love it to organise my thoughts and data.
