### ISSUE TITLE
Cannot update User settings fields in 1.4.0

### ISSUE THREAD

**Issue by farfade** [bakoontz/WikkaWiki#1281]
Hello,

When I try to update a user setting - say the email adress - in 1.4.0, the following error message appears : 

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'theme' in 'field list' in /net/www/wan/wikka/libs/Wakka.class.php:302` 

Regards,

Romain

**Comment by farfade** [comment]
It is an update from the latest previous version (1.3.8 I think)

2018-04-21 11:21 GMT+02:00 Brian Koontz <notifications@github.com>:

> @farfade Is this a new install or an update? If it was an update, what was
> the previous version?
>

**Comment by bakoontz** [comment]
@farfade If you have access to the database, check the wikka_users table for a field that has the name 'theme'.  If it's not there, you can add it:

`ALTER TABLE wikka_users ADD theme varchar(50) default '';`

Strangely, as of 1.3.7 (we didn't have a 1.3.8 release) it should have already been there, so I'm not too sure why it's not there now.

**Comment by farfade** [comment]
Hello @bakoontz,

Thanks for your help. The field was missing but I'm not sure why... I
checked in the inc/db_update script, the lines before and after the one
adding the "theme" column were already OK.

Anyway, it's OK now. Thanks for your help and for this nice software :)

Regards,

Romain

2018-04-29 6:48 GMT+02:00 Brian Koontz <notifications@github.com>:

**Comment by bakoontz** [comment]
@farfade You’re quite welcome!
