### ISSUE TITLE
Space in Heading removes heading

### ISSUE THREAD

**Issue by jugdemon** [bakoontz/WikkaWiki#1282]
I have multiple spaces in the headings in my WikkaWiki. When Softaculous upgraded from 1.3.8 to 1.4, the headings disappear from the page. In the editing mode they are still existent, but inspecting them in the source code mode of the browser shows that they are never loaded from the server.

I assume that some change on back end after 1.3.8 makes it impossible to load headings with spaces inside.

I tested the behaviour for different headings and it always appears.

**Comment by bakoontz** [comment]
Can you post a couple raw markdown examples?

**Comment by jugdemon** [comment]
You can go to the same test page from my other issue: http://scholar.gruebel.io/test

Replace the currently present `======Test======` with `======Test test======` and store the page to see the header disappear.

**Comment by pataphysics** [comment]
I'm seeing the same thing: headings with spaces in them appear in editing mode but don't appear when displayed.

HOWEVER: If bold formatting is added to the heading, it does appear.  So  

==== test text ==== heading does not appear

====  ** test text ** ==== does.

**Comment by bakoontz** [comment]
I'm able to reproduce it.  It's a bug related to #1274.  If you have access to your Wikka install, you can replace line 46 with the following:

``if (!defined('PATTERN_MATCH_HEADINGS')) define('PATTERN_MATCH_HEADINGS', '#^<(h[1-6])(.*?)>\s*?(.*)\s*?</\\1>$#s');``

Tested with the following:

``
===Test Test===
===**Test Test===
===  Test Test  ===
===  **Test Test**  ===
``

I'll include it in the 1.4.1 release.  Thanks for the report!

**Comment by jugdemon** [comment]
@bakoontz When can we expect the release of 1.4.1? I am just trying to way my options, because while it is slightly annoying, I was thinking of just making the headers bold instead of meddling with the install. Softaculous responded so quickly to my request to upgrade to the newer version that I only expect a week delay after you release to get it installed.

Again, thanks for the effort. For now I am only consuming, but I am considering to contribute as this tool is amazing. When I am ready, what is the best way to contribute? Bug fixing, forking and feature implementing?

**Comment by pataphysics** [comment]
I replaced line 46 with the new code, and all headings with and w/o spaces are appearing.  Thanks @bakoontz.

**Comment by bakoontz** [comment]
@jugdemon I’m not opposed to putting out a bug fix release. It’s not like
I’d have thousands complaining :) Give me a week or two if you can, I’ll
find some time to do it. Possibly even this week.

Would appreciate the help.  I can give you push access to the repo. Branch,
fix/add whatever, *please rebase* then submit a pull request.  I’d love to
get some of these bugs worked off first, but whatever you’d like to
contribute would be appreciated!

**Comment by bakoontz** [comment]
@paraphysics Quite welcome, thanks for confirming the fix works.

**Comment by jugdemon** [comment]
@bakoontz I did not mean to push a release, I was rather asking in terms of what is your current expected date for a release. For now I can live with invisible headers, especially since the information is still there while editing. 

I think push access would be a nice start. I would start looking into some bugs, to get a feel of the code base and I'll follow your merge instruction once I actually fix something.

**Comment by bakoontz** [comment]
So I try to aim for a release every 6 months, making the next one October.

I’ll set you up with access.

**Comment by ldemattos** [comment]
I replaced line 46 with the new code, and all headings with and w/o spaces are appearing. Thanks @bakoontz.

**Comment by zorruno** [comment]
@bakoontz, late to the party but just upgraded a wikka site and found this issue, so a note to say thanks for the fix. Thanks also @jugdemon for logging the report :)

**Comment by bakoontz** [comment]
Thanks for the report!

I’m not as active on the project as I once was but I do try to still get
bug fixes in, and I do monitor the issue tracker.
