### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Rasputin2** [bakoontz/WikkaWiki#1301]
I have encountered a couple of problems trying to get WikkaWiki to work on my GoDaddy shared hosting site.  The problem that I am currently stuck on is that this error keeps getting thrown after I fill out and submit my installation page, but if I click on any of the links, I just get returned back to the installation page with all my inputs deleted.  

Can anyone help? 

	if ($config2['wakka_version'] <= '1.3.2')
	{
		print("<p>Almost done! A maintenance operation is needed due to a change in the database structure. This maintenance can be resource consuming if you had many pages. Click on the following link and refresh the page until you see only the text \"Done...\". <a style=\"font-size: 24pt;\" href=\"".WIKKA_BASE_URL."/wikka.php?wakka=Do/maintenance.xml\" target=\"_blank\">Do maintenance.</a></p>");
	}

**Comment by bakoontz** [comment]
John, what version are you upgrading from?

**Comment by Rasputin2** [comment]
Dear Mr. Koontz:

To clarify, I am installing, not upgrading.  The version that the installer wrote in my wikka.config.php file is:
<?php
/**
 * WikkaWiki configuration file 
 * 
 * This file was generated by the Wikka installer on Wed Nov  6 01:13:24 2019
 * Do not manually change wakka_version if you wish to keep your engine up-to-date.
 * Documentation is available at: http://docs.wikkawiki.org/ConfigurationOptions
 */
$wakkaConfig = array(
	'wakka_version' => '1.4.1');
?>

**Comment by Rasputin2** [comment]
Apologies, I hit the "closed" button inadvertently, but just opened it again.

**Comment by bakoontz** [comment]
Nothing further heard on this, but if it's still an issue, please re-open.
