### ISSUE TITLE
PDO Connection Error

### ISSUE THREAD

**Issue by Rasputin2** [bakoontz/WikkaWiki#1302]
I am still trying to install WikkaWikki on my GoDaddy shared hosting site.  I am getting a PDO Connection error.  BY using a series of echo statements in the wikka.php file I managed to narrow down the problem to this specific line:

$wakka = instantiate('Wakka',$wakkaConfig);

When the php code hits this line, it throws the error.  The $wakkaConfig variable is defined as an Array hundreds of lines above this line.  Any help as to what I can do?  If I can't get this to work, I have to uninstall it from GoDaddy and look for other alternatives.

**Comment by bakoontz** [comment]
Sorry about the late reply...most likely if it's a PDO Connection error then the database username and password you entered during installation is incorrect, OR there is a specific hostname you need to provide (which is usually the case with instances of MySQL running in a VM).
