### ISSUE TITLE
No release 1.4.1 on github?

### ISSUE THREAD

**Issue by oemunoz** [bakoontz/WikkaWiki#1304]
Hi, no release on github for 1.4.1?

**Comment by bakoontz** [comment]
Is this what you’re looking for?

https://github.com/bakoontz/WikkaWiki/tree/1.4.1

**Comment by oemunoz** [comment]
Yes, but I make a automatic build from releases:

https://github.com/bakoontz/WikkaWiki/releases

I make a work around for 1.4.1, but is ugly.

https://hub.docker.com/repository/docker/oems/wikkawiki

**Comment by bakoontz** [comment]
Sorry about that, release made!
