### ISSUE TITLE
PDO connection error. 

### ISSUE THREAD

**Issue by isleofwighter** [bakoontz/WikkaWiki#1317]
Suddenly while repeatedly editing a page I get a PDO conneection error. Closing the browser and reentering Wikkawiki I get this same eroor meesage. I am wotking on a local system and I have made no changes to the DB user/pw or anything else.
Been working fine for a week since I installed and have produceed 6/7 pages.

**Comment by bakoontz** [comment]
Can you post a copy of the error you’re getting?

**Comment by isleofwighter** [comment]
Hi

It just said PDO correction problem.

I have since looked into how the user was set up in mysql and updated the number of concurrent connections, connections within an hour etc to 1000, were set to 10 and 100. This solved the problem. Obviously I was going back and forth from edit to view mode and this caused the limits to be exceeded.

You learn something new every day.

Thanks for you help

Mike
