### ISSUE TITLE
Ordered lists aren't displaying and incrementing correctly

### ISSUE THREAD

**Issue by 9strands** [bakoontz/WikkaWiki#1321]
**Issue:** 
  I've been trying to created an ordered list in my local Wikkawiki instance, and the list does get created, but the numbers do not increment.  It also seems to happen in the wikkiwiki.org website

See below screenshot taken on http://docs.wikkawiki.org/FormattingRules on 2020-05-19 @ ~1230AEST:

![image](https://user-images.githubusercontent.com/12106718/82277300-dc7f5f80-99ca-11ea-9380-8f405d1ed45b.png)

The Ordered lists remain with the same list identifier of "1", "A", "I" or "i", for all following entries, even at the same level, on each list, instead of incrementing for each subsequent entry at that level.

This  happens in browsers Firefox, Chrome, and KDE Konqueror and happens on my local 1.4.2 instance as well as on the wikkawiki.org site, so I do not believe it is a browser-specific behavior.

**Expected Behavior:**
~1) List 1
~1) List 2
~1) List 3

Produces a list as follows:
 1. List 1
 2. List 2
 3. List 3

**Actual Behavior:**
~1) List 1
~1) List 2
~1) List 3

Produces a list as follows:
 

` 1. List 1`
` 1. List 2`
` 1. List 3`

![image](https://user-images.githubusercontent.com/12106718/82277919-5bc16300-99cc-11ea-89ee-c54228250aa5.png)

![image](https://user-images.githubusercontent.com/12106718/82277942-68de5200-99cc-11ea-881a-48fda83a2adf.png)

Versions:
- Apache 2.4.34
```# ./usr/sbin/httpd -v
Server version: Apache/2.4.34 (Red Hat)
Server built:   Nov 14 2019 10:41:27```

- WikkaWiki 1.4.2
```# grep git_version version.php 
$git_version = '1.4.2';
if (!defined('WAKKA_VERSION')) define('WAKKA_VERSION', $git_version);
```

- PHP

```# ./php --version
PHP 7.3.11 (cli) (built: Oct 31 2019 08:30:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
# ./php -m
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

#```

**Comment by bakoontz** [comment]
I’ll take a look. Everything is rendered server-side so you’re correct in
that it’s not a browser issue.

Brian

**Comment by 9strands** [comment]
Cheers! Thanks, Brian!

**Comment by bakoontz** [comment]
#1078 broke this.  Reverting changes from that issue to resolve numbering.  Line breaks between lists are still problematic.
