### ISSUE TITLE
After upgrading from 1.3.3 to 1.4.2: can’t change password, new user can only login once

### ISSUE THREAD

**Issue by unor** [bakoontz/WikkaWiki#1326]
I upgraded an installation from 1.3.3 to 1.4.2. The admin forgot their password, they tried the password reminder, but the sent password didn’t work (probably because of #1310). I tried to set a new password for the admin user directly in the database; after some tries with different encryption methods, I found one that worked (can’t remember which one).

The admin user can login now, but changing their password at UserSettings doesn’t seem to work or has no effect (can’t remember, and can’t test it right now).

Then I registered another user account. Logging in with the new account works, but only for the first login. After logging out and trying to login again, it fails with "Sorry, you entered the wrong password." While being logged in (right after registration), I can’t change the password (it fails with "The old password you entered is wrong.").

I registered the user with the password "example". In the database, the password gets saved as `$2y$10$ud29YKUgIVa7GKasRFJGLe9Qj`. When requesting a password reminder, the reminder in the email is this very same string: `$2y$10$ud29YKUgIVa7GKasRFJGLe9Qj`.

**Q1:** How to fix this?

**Q2:** How can I manually encrypt a password for WikkaWiki 1.4.2, so that I can enter it directly into the database? (related: #1311)

**Comment by bakoontz** [comment]
Sorry for the delay in getting back to you on this. 

Q2: Generate the password hash using the PHP password_hash() function, then insert it into the DB record:
```
sh> php -r 'echo password_hash("somePassword", PASSWORD_DEFAULT);'
mysql> update wikka_users set password='passwordhash' where user='SomeUser';
```

**Comment by unor** [comment]
Thanks, bakoontz! I just tested it with the non-admin user. For testing, I used [this password_hash generator](https://php-password-hash-online-tool.herokuapp.com/password_hash).

I tried to insert the hash in the database, but it failed because of length. The `password` field was set to `varchar(32)`. Based on the recommendation on https://www.php.net/password_hash, I changed it to `varchar(255)`. After this, I could paste the hash, and logging in with the new password worked fine.

Then I tried to change the password via the UserSettings page. It displayed the success message, but the hash in the database didn’t change, so I can’t login with the changed password, but logging in with the password I entered directly in the DB still works.

(Regarding the CSRF token issue, I always visit the wiki’s homepage and go back to the login page (or make a cache-refresh), after which it seems to work.)

**Comment by bakoontz** [comment]
I think there might be some confusion here...there are two password fields:

```
mysql> describe wikka_users;
+-------------------------+-----------------------------------------------------
--------------------------+------+-----+---------------------+-------+
| Field                   | Type
                          | Null | Key | Default             | Extra |
+-------------------------+-----------------------------------------------------
--------------------------+------+-----+---------------------+-------+
...
| password                | varchar(255)
                          | NO   |     |                     |       |
...
...
| md5_password            | varchar(32)
                          | NO   |     |       
```
The 'password' field stores the PHP-generated password_hash.  The 'md5_password' stores the old-style MD5 hash.  If 'password' is set, 'md5_password' is ignored during authentication.    It think that somehow you are getting them mixed up. But apparently they are getting mixed up in the right way, since you're able to log in now!

**Comment by unor** [comment]
I don’t have `md5_password`. These are the fields I see in Adminer:

    name
    password
    email
    revisioncount
    changescount
    doubleclickedit
    signuptime
    show_comments
    status
    theme
    default_comment_display
    challenge

**Comment by bakoontz** [comment]
Ah, that is problematic.  What upgrade path did you take?  If you copied over the previous install with 1.4.2, then when you refreshed you should have been given the option to upgrade the database.  I really can't even begin to predict what the behavior will be if you're running 1.4.2 without the DB updates.

A couple of suggestions (after backing everything up!): In wikka.config.php, reset the wakka_version parameter to the previous version, then refresh the page and follow the prompts.  Or, you can look at setup/inc/db_update_mysql.php and do the updates manually starting with the case statement that matches the previous version you're updating from.

**Comment by unor** [comment]
> What upgrade path did you take?

IIRC, I followed "Method A" from http://docs.wikkawiki.org/UpgradeNotes, and after the web-based updater was finished, I manually replaced the `uploads` folder and the `robots.txt` file.

> In wikka.config.php, reset the wakka_version parameter to the previous version, then refresh the page and follow the prompts.

I will try that.

**Comment by unor** [comment]
I set it to

    'wakka_version' => '1.3.3',

and started the web updater. The updater ran successfully, but it never said that it updates the DB.

**Comment by bakoontz** [comment]
Try again, but set the version to '1.3.6'.

**Comment by unor** [comment]
This seems to have worked! The web updater said:

> 1.3.5 to 1.3.6 changes:
> Changing "default" theme references to "classic" theme ... OK
> 1.3.7 to 1.4.0 changes:
> Altering pages table structure... OK
> Altering referrers table structure... OK
> Altering users table structure... OK
> Altering comments table structure... OK
> 1.4.0 to 1.4.1 changes:
> mysqlAdding/Updating default page WikkaInstaller... OK
> Altering users table structure (default_comment_display)... OK
> Adding WikkaInstaller user... OK
> 1.4.1 to 1.4.2 changes:
> Altering users table structure... OK

and now there is the `md5_password` field in the table.

Changing the password at UserSettings seems to work fine, too.

Thank you :)

**Comment by bakoontz** [comment]
Of course!  You actually uncovered a different bug:  The 1.3.3 version wasn't in the update file, so the update was never triggered which is why your DB never updated.  Glad it's working now.
