### ISSUE TITLE
Incorrect password storage

### ISSUE THREAD

**Issue by wikkawik** [bakoontz/WikkaWiki#525]
NOTE: found this in 1.1.6.3 but the problem still exists in current trunk.

The usersettings action stores each new password as md5(mysql_real_escape_string([password])); the only validation check is that the password must be longer than a minimum and not contain a '''space'''.
When a use logs in, the typed-in password is compared to md5([password]).

Unfortunately, given the validation that is done now, there is no guarantee that md5(mysql_real_escape_string([password])) === md5([password]).

For instance, if user JohnDoe creates an account and chooses password '''jane'doe''', this will be stored as the md5 of '''jane\'doe''' (mysql_real_escape_string() adds the slash!). Next time JohnDoe tries to log in,  he types '''jane'doe''' as his password, the md5 of this is taken, and compared to what's stored. And he won't be allowed to log in with this, because md5("jane'doe") !== md5("jane\'doe")!

My proposal:
1. disallow not only space, but ''all'' whitespace and the ''null'' character in a password; allow everything else so a user can choose a "strong" password
2. store the md5 of the validated password: the result won't contain any "dangerous" characters, so mysql_real_escape_string() is not necessary!

(Set component as 'core' since this is core functionality, even though it's implemented in an action.)

**Comment by bakoontz** [comment]
MD5 authentication is deprecated as of 1.4.2 and will be removed in a future version.
