### ISSUE TITLE
Prevent old revisions from being indexed by search engines

### ISSUE THREAD

**Issue by wikkawik** [bakoontz/WikkaWiki#553]
Hi,

I'm the manager of Kikipedia - an encyclopedia in Hebrew. And I'm using your system and I'm very happy with the system.
Google has been indexing Kikipedia and the site is shown, in many cases, as the first result by Google.

A sample Google search: http://www.google.com/search?hl=en&q=%D7%A1%D7%98%D7%95%D7%91%D7%99%D7%A0%D7%92

The problem is that many of these links point to a "/revisions.xml" page and/or to a page with a "show" and/or "time" variables.

These links point to a dead-end in Kikipedia and I have no idea what to do nor why this happens.

Sample of two links: (SearchedWord = the searched word)
http://www.humor.co.il/kiki/kikipedia.php?wakka='''SearchedWord'''/show&time=.2007-08-01+07%3A06%3A49
http://www.humor.co.il/kiki/kikipedia.php?wakka='''SearchedWord'''/revisions.xml

Please help.
Thanks

=== Coordination ticket ===
- #595

**Comment by bakoontz** [comment]
This is more of an issue with the site admin setting up the appropriate restrictions to prevent access to certain handlers.  robots.txt is just a recommendation, and won't stop any search engine from indexing these pages.  The best solutions are to make these handlers admin-only, block them at the HTTP level, or simply move the handlers out of the way so they cannot be resolved.
